// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; aliases?: string[]; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "api-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/api-keys",
    "summary": "Create an api key",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/api-keys/{id}",
    "summary": "Delete an api key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/api-keys",
    "summary": "List api keys",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "attachments",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/attachments",
    "summary": "Create an attachment",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/attachments/{id}",
    "summary": "Get an attachment",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "billing",
  "routes": [
   {
    "name": "checkout",
    "method": "POST",
    "path": "/api/v1/billing/checkout",
    "summary": "POST /checkout {tier} — create a Plugipay hosted checkout session for a paid tier; the browser redirects to data.hostedUrl.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "tier",
      "kind": "string",
      "required": true,
      "choices": [
       "free",
       "starter",
       "growth",
       "business"
      ]
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/billing",
    "summary": "Current subscription (free default when no row) + the tier table the portal renders.",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "canned-replies",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/canned-replies",
    "summary": "Create a canned reply",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "title",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/canned-replies/{id}",
    "summary": "Delete a canned reply",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/canned-replies",
    "summary": "List canned replies",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/canned-replies/{id}",
    "summary": "Update a canned reply",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "title",
      "kind": "string",
      "required": false
     },
     {
      "name": "body",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "channels",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/channels",
    "summary": "Create a channel",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "provider",
      "kind": "string",
      "required": false,
      "choices": [
       "whatsapp_twilio",
       "whatsapp_cloud",
       "email_resend",
       "telegram_bot",
       "slack_webhook",
       "discord_webhook"
      ]
     },
     {
      "name": "accountSid",
      "kind": "string",
      "required": false
     },
     {
      "name": "authToken",
      "kind": "string",
      "required": false
     },
     {
      "name": "whatsappNumber",
      "kind": "string",
      "required": false
     },
     {
      "name": "displayName",
      "kind": "string",
      "required": false
     },
     {
      "name": "accessToken",
      "kind": "string",
      "required": false
     },
     {
      "name": "phoneNumberId",
      "kind": "string",
      "required": false
     },
     {
      "name": "wabaId",
      "kind": "string",
      "required": false
     },
     {
      "name": "displayNumber",
      "kind": "string",
      "required": false
     },
     {
      "name": "verifyToken",
      "kind": "string",
      "required": false
     },
     {
      "name": "appSecret",
      "kind": "string",
      "required": false
     },
     {
      "name": "apiKey",
      "kind": "string",
      "required": false
     },
     {
      "name": "fromEmail",
      "kind": "string",
      "required": false
     },
     {
      "name": "fromName",
      "kind": "string",
      "required": false
     },
     {
      "name": "botToken",
      "kind": "string",
      "required": false
     },
     {
      "name": "webhookUrl",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/channels/{id}",
    "summary": "Delete a channel",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/channels",
    "summary": "List channels",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "csat",
  "routes": [
   {
    "name": "stats",
    "method": "GET",
    "path": "/api/v1/csat/stats",
    "summary": "List stats",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "domains",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/domains",
    "summary": "Create a domain",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "domain",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/domains/{id}",
    "summary": "Delete a domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/domains",
    "summary": "List domains",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "verify",
    "method": "POST",
    "path": "/api/v1/domains/{id}/verify",
    "summary": "Verify a domain",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "help",
  "routes": [
   {
    "name": "articles",
    "method": "GET",
    "path": "/api/v1/help/articles",
    "summary": "List articles",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "create-articles",
    "method": "POST",
    "path": "/api/v1/help/articles",
    "summary": "Create an article",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "kind",
      "kind": "string",
      "required": false,
      "choices": [
       "faq",
       "article"
      ]
     },
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "category",
      "kind": "string",
      "required": false
     },
     {
      "name": "title",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "draft",
       "published"
      ]
     },
     {
      "name": "position",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "delete-articles",
    "method": "DELETE",
    "path": "/api/v1/help/articles/{id}",
    "summary": "Delete an article",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "get-articles",
    "method": "GET",
    "path": "/api/v1/help/articles/{id}",
    "summary": "Get an article",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "articles-2"
    ]
   },
   {
    "name": "update-articles",
    "method": "PATCH",
    "path": "/api/v1/help/articles/{id}",
    "summary": "Update an article",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "kind",
      "kind": "string",
      "required": false,
      "choices": [
       "faq",
       "article"
      ]
     },
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "category",
      "kind": "string",
      "required": false
     },
     {
      "name": "title",
      "kind": "string",
      "required": false
     },
     {
      "name": "body",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "draft",
       "published"
      ]
     },
     {
      "name": "position",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "me",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/me",
    "summary": "List me",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "profile",
  "routes": [
   {
    "name": "avatar",
    "method": "GET",
    "path": "/api/v1/profile/avatar/{sub}",
    "summary": "Get an avatar",
    "pathParams": [
     "sub"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "delete-avatar",
    "method": "DELETE",
    "path": "/api/v1/profile/avatar",
    "summary": "Delete avatar",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "set-avatar",
    "method": "PUT",
    "path": "/api/v1/profile/avatar",
    "summary": "Set avatar",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "public",
  "routes": [
   {
    "name": "create-tickets",
    "method": "POST",
    "path": "/api/v1/public/tickets",
    "summary": "Create a ticket",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "accountId",
      "kind": "string",
      "required": true
     },
     {
      "name": "subject",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "email",
      "kind": "string",
      "required": true
     },
     {
      "name": "name",
      "kind": "string",
      "required": false
     },
     {
      "name": "company",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "create-tickets-attachments",
    "method": "POST",
    "path": "/api/v1/public/tickets/{accessToken}/attachments",
    "summary": "Attachments a ticket",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "domains-provision-callback",
    "method": "POST",
    "path": "/api/v1/public/domains/provision-callback",
    "summary": "Create a provision callback",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "domain",
      "kind": "string",
      "required": true
     },
     {
      "name": "status",
      "kind": "string",
      "required": true,
      "choices": [
       "success",
       "failed"
      ]
     },
     {
      "name": "error",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "domains-resolve",
    "method": "GET",
    "path": "/api/v1/public/domains/resolve",
    "summary": "Host → accountId — used by the frontend middleware to route a custom domain's request to the right workspace.",
    "pathParams": [],
    "query": [
     {
      "name": "host",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "help",
    "method": "GET",
    "path": "/api/v1/public/help/{accountId}",
    "summary": "The help-center bundle.",
    "pathParams": [
     "accountId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "help-a",
    "method": "GET",
    "path": "/api/v1/public/help/{accountId}/a/{slug}",
    "summary": "A single published article.",
    "pathParams": [
     "accountId",
     "slug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "help-branding",
    "method": "GET",
    "path": "/api/v1/public/help/{accountId}/branding",
    "summary": "Public branding (logo + colors + name) for the help center AND the hosted portal's pre-auth screen.",
    "pathParams": [
     "accountId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "help-logo",
    "method": "GET",
    "path": "/api/v1/public/help/{accountId}/logo",
    "summary": "Serve the uploaded brand logo bytes.",
    "pathParams": [
     "accountId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "help-search",
    "method": "GET",
    "path": "/api/v1/public/help/{accountId}/search",
    "summary": "List search",
    "pathParams": [
     "accountId"
    ],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "requester-verify",
    "method": "POST",
    "path": "/api/v1/public/requester/verify",
    "summary": "Create a verify",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "token",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "tickets",
    "method": "GET",
    "path": "/api/v1/public/tickets/{accessToken}",
    "summary": "Tokenized status view — public messages only, no internal notes.",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "tickets-attachments",
    "method": "GET",
    "path": "/api/v1/public/tickets/{accessToken}/attachments/{id}",
    "summary": "Get an attachment",
    "pathParams": [
     "accessToken",
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "tickets-csat",
    "method": "POST",
    "path": "/api/v1/public/tickets/{accessToken}/csat",
    "summary": "Csat a ticket",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": [
     {
      "name": "score",
      "kind": "number",
      "required": true
     },
     {
      "name": "comment",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "tickets-messages",
    "method": "POST",
    "path": "/api/v1/public/tickets/{accessToken}/messages",
    "summary": "Messages a ticket",
    "pathParams": [
     "accessToken"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "attachmentIds",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "widget-config",
    "method": "GET",
    "path": "/api/v1/public/widget-config",
    "summary": "Pre-ticket config for the embeddable widget + hosted form (the branding footer renders before any ticket exists).",
    "pathParams": [],
    "query": [
     {
      "name": "account",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "reports",
  "routes": [
   {
    "name": "summary",
    "method": "GET",
    "path": "/api/v1/reports/summary",
    "summary": "List summary",
    "pathParams": [],
    "query": [
     {
      "name": "days",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "requester",
  "routes": [
   {
    "name": "create-tickets",
    "method": "POST",
    "path": "/api/v1/requester/tickets",
    "summary": "Create a ticket",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "subject",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "get-tickets",
    "method": "GET",
    "path": "/api/v1/requester/tickets/{number}",
    "summary": "Get a ticket",
    "pathParams": [
     "number"
    ],
    "query": [],
    "body": null,
    "aliases": [
     "tickets-2"
    ]
   },
   {
    "name": "me",
    "method": "GET",
    "path": "/api/v1/requester/me",
    "summary": "List me",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "tickets",
    "method": "GET",
    "path": "/api/v1/requester/tickets",
    "summary": "List tickets",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "open",
       "resolved",
       "all"
      ]
     }
    ],
    "body": null
   },
   {
    "name": "tickets-messages",
    "method": "POST",
    "path": "/api/v1/requester/tickets/{number}/messages",
    "summary": "Messages a ticket",
    "pathParams": [
     "number"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "settings",
  "routes": [
   {
    "name": "automation",
    "method": "GET",
    "path": "/api/v1/settings/automation",
    "summary": "List automation",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "branding",
    "method": "GET",
    "path": "/api/v1/settings/branding",
    "summary": "List branding",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "create-branding-logo",
    "method": "POST",
    "path": "/api/v1/settings/branding/logo",
    "summary": "Create a logo",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "length",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete-branding-logo",
    "method": "DELETE",
    "path": "/api/v1/settings/branding/logo",
    "summary": "Delete logo",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "help",
    "method": "GET",
    "path": "/api/v1/settings/help",
    "summary": "List help",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "set-automation",
    "method": "PUT",
    "path": "/api/v1/settings/automation",
    "summary": "Set automation",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "businessHours",
      "kind": "json",
      "required": false
     },
     {
      "name": "autoResponseEnabled",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "autoResponseInside",
      "kind": "string",
      "required": false
     },
     {
      "name": "autoResponseOutside",
      "kind": "string",
      "required": false
     },
     {
      "name": "hideBranding",
      "kind": "boolean",
      "required": false
     }
    ]
   },
   {
    "name": "set-branding",
    "method": "PUT",
    "path": "/api/v1/settings/branding",
    "summary": "Set branding",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "slug",
      "kind": "string",
      "required": false
     },
     {
      "name": "brandName",
      "kind": "string",
      "required": false
     },
     {
      "name": "brandLogoUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "accentColor",
      "kind": "string",
      "required": false
     },
     {
      "name": "brandColor",
      "kind": "string",
      "required": false
     },
     {
      "name": "widgetTextColor",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "set-help",
    "method": "PUT",
    "path": "/api/v1/settings/help",
    "summary": "Set help",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "contactEmail",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactPhone",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactAddress",
      "kind": "string",
      "required": false
     },
     {
      "name": "docsUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "contactUrl",
      "kind": "string",
      "required": false
     },
     {
      "name": "helpIntro",
      "kind": "string",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "tickets",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/tickets",
    "summary": "Agent-created ticket (logging an inquiry that arrived out-of-band, e.g.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "subject",
      "kind": "string",
      "required": true
     },
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "requesterEmail",
      "kind": "string",
      "required": true
     },
     {
      "name": "requesterName",
      "kind": "string",
      "required": false
     },
     {
      "name": "priority",
      "kind": "string",
      "required": false
     },
     {
      "name": "channel",
      "kind": "string",
      "required": false,
      "choices": [
       "web",
       "email",
       "whatsapp"
      ]
     }
    ]
   },
   {
    "name": "get",
    "method": "GET",
    "path": "/api/v1/tickets/{id}",
    "summary": "Get a ticket",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/tickets",
    "summary": "List tickets",
    "pathParams": [],
    "query": [
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "open",
       "pending",
       "resolved",
       "closed",
       "all"
      ]
     },
     {
      "name": "assignee",
      "kind": "string",
      "required": false
     },
     {
      "name": "tag",
      "kind": "string",
      "required": false
     },
     {
      "name": "channel",
      "kind": "string",
      "required": false,
      "choices": [
       "web",
       "email",
       "whatsapp",
       "telegram"
      ]
     },
     {
      "name": "priority",
      "kind": "string",
      "required": false,
      "choices": [
       "low",
       "normal",
       "high",
       "urgent"
      ]
     },
     {
      "name": "q",
      "kind": "string",
      "required": false
     },
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "messages",
    "method": "POST",
    "path": "/api/v1/tickets/{id}/messages",
    "summary": "Messages a ticket",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "body",
      "kind": "string",
      "required": true
     },
     {
      "name": "isInternal",
      "kind": "boolean",
      "required": false
     },
     {
      "name": "authorName",
      "kind": "string",
      "required": false
     },
     {
      "name": "attachmentIds",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "tags",
    "method": "GET",
    "path": "/api/v1/tickets/tags",
    "summary": "Distinct tags across the workspace's tickets — autocomplete feed. (Must be mounted before /:id so 'tags' isn't read as a ticket id.)",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/tickets/{id}",
    "summary": "Update a ticket",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "status",
      "kind": "string",
      "required": false
     },
     {
      "name": "priority",
      "kind": "string",
      "required": false
     },
     {
      "name": "assigneeSub",
      "kind": "string",
      "required": false
     },
     {
      "name": "tags",
      "kind": "array",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "webhook-subscriptions",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "Register an endpoint.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Delete a webhook subscription",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries",
    "summary": "List webhook deliveries.",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "number",
      "required": false
     },
     {
      "name": "cursor",
      "kind": "string",
      "required": false
     },
     {
      "name": "subscriptionId",
      "kind": "string",
      "required": false
     },
     {
      "name": "status",
      "kind": "string",
      "required": false,
      "choices": [
       "pending",
       "succeeded",
       "failed"
      ]
     },
     {
      "name": "type",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "deliveries-retry",
    "method": "POST",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}/retry",
    "summary": "Retry a webhook delivery.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "event-types",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/event-types",
    "summary": "The event types a subscription can receive, with what each one means.",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "get-deliveries",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions/deliveries/{id}",
    "summary": "Get a webhook delivery, with every attempt made at it.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/webhook-subscriptions",
    "summary": "List webhook subscriptions",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "update",
    "method": "PATCH",
    "path": "/api/v1/webhook-subscriptions/{id}",
    "summary": "Update a subscription. `active: false` pauses it (its queued deliveries become failed); `active: true` re-enables it — also after Suppuo switched it off for failing — and clears its failure streak.",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": false
     },
     {
      "name": "events",
      "kind": "array",
      "required": false
     },
     {
      "name": "active",
      "kind": "boolean",
      "required": false
     }
    ]
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      for (const name of [route.name, ...(route.aliases ?? [])]) {
      const cmd = new Command(name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd, { hidden: name !== route.name });
      }
    }
    api.addCommand(group);
  }
  return api;
}
